management:
  metrics:
    export:
      nightingale:
        addr: "http://192.168.1.1:2080/v1/push"
        endpoint: "192.168.1.1"
        step: 10s
        append-tags: "key=value"
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com.lynxcat: debug
